FROM python:latest
WORKDIR /app
COPY . /app/

RUN apt-get update
RUN apt-get install build-essential
RUN pip install fastapi uvicorn
RUN pip install python-dotenv pydantic-settings
EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
